default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5433
  username: escolheai
  password: <%= ENV["ESCOLHEAI_DATABASE_PASSWORD"] %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: escolhe_ai_development

test:
  <<: *default
  database: escolhe_ai_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
