service: escolhe_ai

image: jou82/escolhe_ai

servers:
  web:
    hosts:
      - 188.245.192.222
    options:
      add-host: host.docker.internal:host-gateway

proxy:
  app_port: 3000
  hosts:
    - escolheai.net
    - www.escolheai.net
  ssl: true
  healthcheck:
    path: /up
    interval: 3
    timeout: 30

registry:
  server: docker.io
  username: jou82
  password:
    - DOCKERHUB_PASSWORD

builder:
  arch: amd64

env:
  clear:
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - CLOUDINARY_CLOUD_NAME
    - CLOUDINARY_API_KEY
    - CLOUDINARY_API_SECRET
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET

